name: Build PDF

on:
  push:
    branches:
      - main

env:
  DAY_OF_WEEK: Monday


jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-base texlive-latex-extra

    - name: Compile LaTeX
      run: cd V1 && pdflatex -interaction=nonstopmode -halt-on-error v1.tex

    - name: Get release name from file
      id: get_version
      run: echo ::set-output name=version::$(cat version)

    - name: Verify PDF file exists
      run: |
        if [ ! -f V1/v1.pdf ]; then
          echo "PDF file not found"
          exit 1
        elif [ ! -s V1/v1.pdf ]; then
          echo "PDF file is empty"
          exit 1
        else
          echo "PDF file generated successfully"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: refs/tags/v${{ steps.get_version.outputs.version }}
        release_name: ${{ steps.get_version.outputs.version }}
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: V1/v1.pdf
        asset_name: v1.pdf
        asset_content_type: application/pdf


