name: Compile and push PDF

on:
  push:
    branches:
      - main

env:
  DAY_OF_WEEK: Monday

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: docker --version

    - name: Build packagae
      run: ./run.sh


    - name: Get version from file
      id: get_version
      run: echo ::set-output name=version::$(cat version)

    - name: Verify PDF file exists
      run: |
        if [ ! -f v1.pdf ]; then
          echo "PDF file not found"
          exit 1
        elif [ ! -s V1.pdf ]; then
          echo "PDF file is empty"
          exit 1
        else
          echo "PDF file generated successfully"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: ${{ steps.get_version.outputs.version }}
        body: ${{ github.event.head_commit.message }}


    - name: Upload PDF
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: v1.pdf
        asset_name: v1.pdf
        asset_content_type: application/pdf
